var config = require(__dirname + '/config');
var watchJob = require(__dirname + '/jobs/watchpaymentjob');
var blockJob = require(__dirname + '/jobs/lastblockjob');
var webhooksJob = require(__dirname + '/jobs/webhooksjob');
var path = require('path');
var express = require('express');
var app = express();
app.set('view engine', 'ejs');
app.set('views', __dirname + '/views');
app.use(express.bodyParser());
app.use(express.static(path.join(__dirname, 'public')));

require(__dirname + '/db').instantiateDb();
require(__dirname + '/routes')(app);
require('bitstamped');
blockJob.runLastBlockJob();
watchJob.runWatchPaymentsJob();
webhooksJob.runWebhooksJob();
app.listen(config.port);
console.log('CouchDB server:    ' + config.couchdb.url + '/' + config.couchdb.name);
console.log('Bitcoind RPC:      ' + config.bitcoind.host + ':' + config.bitcoind.port);
console.log('Baron listening:   http://0.0.0.0:' + config.port);
